---
- name: setup
  junos_config:
    lines:
      - delete firewall family inet filter Ansible-test term ansible then accept
    host: "{{ inventory_hostname }}"
    username: "{{ junos_user }}"
    password: "{{ junos_pass }}"
    transport: netconf
