 $ANSIBLE_VAULT;1.1;AES256
66323330346432633839373730623764376430393734643062353562393039393232613034623062
6661343432656463626336383033313362393033326438630a623439363535616638356665386630
36393762303338313937646433376465333531323031616262643230663839623865653433396335
6535363862306530360a393963633762343130386431396361323965363632616235343934383136
64373762306266303766656331653234623735326463393932633636343938663064396530333063
35366533336338383236303164323365336635636164333365643362343534616337633339626363
62393562333535363263396664623763346439613130613861663934383364663535653662343535
38373230336433396438333239653932333466393263633564376463383131656135663334353130
37393730323038303235666264363734646463323139346162613137393865333433313232333065
36626639343932383266366133353166393439613963663536656531613863633532643065386263
306462343466316166323664633631396166
