---
- name: setup snmp
  junos_config:
    lines:
      - set snmp community public
      - set snmp community public authorization read-only
      - set snmp community public clients 192.168.1.0/24
      - set snmp community public clients 192.168.1.0/24 restrict
    host: "{{ inventory_hostname }}"
    username: "{{ junos_user }}"
    password: "{{ junos_pass }}"
    transport: netconf
